full_args <- commandArgs(trailingOnly = FALSE)
script_arg <- grep("^--file=", full_args, value = TRUE)
stopifnot(length(script_arg) == 1L)
script_path <- normalizePath(sub("^--file=", "", script_arg), mustWork = TRUE)
repo_root <- normalizePath(file.path(dirname(script_path), "../../.."), mustWork = TRUE)

data_root <- "/mnt/f/spatialecotyper_reproduction"
official_repo <- "/mnt/c/Users/Microsoft/Documents/EBV开题/external/spatialecotyper-official"
official_commit <- "48c2c846781d3a312771021c1a2ef5fc383700c5"
raw_dir <- file.path(data_root, "raw", "tutorial")
work_root <- file.path(data_root, "work", "tutorials")
result_root <- file.path(data_root, "results", "tutorials")
manifest_path <- file.path(data_root, "archive", "manifests", "tutorial-files.downloaded.tsv")
checksum_path <- file.path(data_root, "archive", "manifests", "tutorial-files.sha256")
environment_lock <- file.path(data_root, "archive", "manifests", "renv.lock")
status_path <- file.path(result_root, "run-status.tsv")
order_path <- file.path(repo_root, "reproduction", "spatialecotyper", "config", "tutorial-order.tsv")

sha256_file <- function(path) {
  output <- system2("sha256sum", shQuote(path), stdout = TRUE, stderr = TRUE)
  status <- attr(output, "status")
  if (!is.null(status) && status != 0L) {
    stop(paste(output, collapse = "\n"))
  }
  sub("[[:space:]].*$", "", output[[1]])
}

verify_source <- function() {
  observed <- system2(
    "git", c("-C", shQuote(official_repo), "rev-parse", "HEAD"),
    stdout = TRUE
  )
  stopifnot(identical(observed, official_commit))
}

verify_archive <- function() {
  output <- system2(
    "sha256sum", c("--check", shQuote(checksum_path)),
    stdout = TRUE, stderr = TRUE
  )
  status <- attr(output, "status")
  if (!is.null(status) && status != 0L) {
    stop(paste(output, collapse = "\n"))
  }
  invisible(output)
}

prepare_runtime_rmd <- function(tutorial_id, rmd_name) {
  original <- file.path(official_repo, "vignettes", rmd_name)
  work_dir <- file.path(work_root, tutorial_id)
  result_dir <- file.path(result_root, tutorial_id)
  dir.create(work_dir, recursive = TRUE, showWarnings = FALSE)
  dir.create(result_dir, recursive = TRUE, showWarnings = FALSE)

  runtime <- file.path(work_dir, rmd_name)
  text <- readLines(original, warn = FALSE)
  manifest <- read.delim(manifest_path, stringsAsFactors = FALSE, check.names = FALSE)
  stopifnot(nrow(manifest) == 21L)
  input_adapter <- "official_urls_to_sha256_verified_local_archive"
  strict_material_status <- "PASS"
  strict_material_issue <- ""
  adapted_input_sha256 <- ""
  for (i in seq_len(nrow(manifest))) {
    local_path <- file.path(raw_dir, manifest$file[[i]])
    stopifnot(file.exists(local_path), file.info(local_path)$size > 0)
    if (tutorial_id == "T02" &&
        manifest$file[[i]] == "Melanoma1_subset_SpatialEcoTyper_results.rds") {
      archived_result <- readRDS(local_path)
      archived_fields <- colnames(archived_result$obj@meta.data)
      if (!all(c("Spot.X", "Spot.Y") %in% archived_fields)) {
        upstream_path <- file.path(
          work_root, "T01", "Melanoma1_subset_SpatialEcoTyper_results.rds"
        )
        stopifnot(file.exists(upstream_path), file.info(upstream_path)$size > 0)
        local_path <- upstream_path
        input_adapter <- paste0(
          input_adapter,
          ";T02_uses_T01_official_output"
        )
        strict_material_status <- "FAIL_INPUT_SCHEMA_WITH_OFFICIAL_UPSTREAM_FALLBACK"
        strict_material_issue <- paste0(
          "Archived melanoma RDS lacks Spot.X/Spot.Y required by fixed ",
          "AnnotateCells; substituted output generated by official T01"
        )
        adapted_input_sha256 <- sha256_file(upstream_path)
      }
    }
    text <- gsub(manifest$url[[i]], local_path, text, fixed = TRUE)
  }
  writeLines(text, runtime, useBytes = TRUE)

  images_source <- file.path(official_repo, "vignettes", "images")
  images_target <- file.path(work_dir, "images")
  if (dir.exists(images_source) && !dir.exists(images_target)) {
    copied <- file.copy(images_source, work_dir, recursive = TRUE)
    stopifnot(isTRUE(copied), dir.exists(images_target))
  }

  list(
    original = original,
    runtime = runtime,
    work_dir = work_dir,
    result_dir = result_dir,
    input_adapter = input_adapter,
    strict_material_status = strict_material_status,
    strict_material_issue = strict_material_issue,
    adapted_input_sha256 = adapted_input_sha256,
    output_html = file.path(
      result_dir,
      paste0(tools::file_path_sans_ext(rmd_name), ".html")
    )
  )
}

render_one <- function(tutorial_id) {
  order <- read.delim(order_path, stringsAsFactors = FALSE)
  row <- order[order$tutorial_id == tutorial_id, , drop = FALSE]
  stopifnot(nrow(row) == 1L)
  paths <- prepare_runtime_rmd(tutorial_id, row$rmd[[1]])
  options(width = 120)
  render_env <- new.env(parent = globalenv())
  render_env$download.file <- function(url, destfile, ...) {
    if (length(url) == 1L && file.exists(url)) {
      copied <- file.copy(url, destfile, overwrite = TRUE)
      if (!isTRUE(copied)) stop(sprintf("Failed to stage archived input: %s", url))
      return(invisible(0L))
    }
    utils::download.file(url, destfile, ...)
  }
  rmarkdown::render(
    input = paths$runtime,
    output_format = "html_document",
    output_file = basename(paths$output_html),
    output_dir = paths$result_dir,
    intermediates_dir = paths$work_dir,
    knit_root_dir = paths$work_dir,
    clean = FALSE,
    envir = render_env,
    quiet = FALSE
  )
  stopifnot(file.exists(paths$output_html), file.info(paths$output_html)$size > 0)
}

trailing <- commandArgs(trailingOnly = TRUE)
if (length(trailing) == 2L && identical(trailing[[1]], "--render-one")) {
  verify_source()
  verify_archive()
  render_one(trailing[[2]])
  quit(save = "no", status = 0L)
}

if (length(trailing)) {
  stop("Usage: run_tutorials.R [--render-one TUTORIAL_ID]")
}

verify_source()
verify_archive()
stopifnot(file.exists(environment_lock))
dir.create(work_root, recursive = TRUE, showWarnings = FALSE)
dir.create(result_root, recursive = TRUE, showWarnings = FALSE)

order <- read.delim(order_path, stringsAsFactors = FALSE)
stopifnot(nrow(order) == 8L, identical(order$order, 1:8))
environment_sha <- sha256_file(environment_lock)

if (file.exists(status_path)) {
  records <- read.delim(status_path, stringsAsFactors = FALSE, check.names = FALSE)
} else {
  records <- data.frame()
}
if (nrow(records) && !"strict_material_status" %in% names(records)) {
  records$strict_material_status <- "PASS"
}
if (nrow(records) && !"strict_material_issue" %in% names(records)) {
  records$strict_material_issue <- ""
}
if (nrow(records) && !"adapted_input_sha256" %in% names(records)) {
  records$adapted_input_sha256 <- ""
}

write_records <- function(records) {
  records <- records[base::order(records$order), , drop = FALSE]
  temp <- paste0(status_path, ".part")
  write.table(records, temp, sep = "\t", row.names = FALSE, quote = FALSE, na = "")
  stopifnot(file.rename(temp, status_path))
  invisible(records)
}

for (i in seq_len(nrow(order))) {
  tutorial_id <- order$tutorial_id[[i]]
  prior <- if (nrow(records)) records[records$tutorial_id == tutorial_id, , drop = FALSE] else data.frame()
  if (nrow(prior) == 1L && identical(prior$status[[1]], "PASS") &&
      file.exists(prior$rendered_html[[1]])) {
    message(sprintf("[%s] already PASS; skipping", tutorial_id))
    next
  }

  paths <- prepare_runtime_rmd(tutorial_id, order$rmd[[i]])
  log_path <- file.path(paths$result_dir, "render.log")
  time_path <- file.path(paths$result_dir, "time-v.txt")
  started <- format(Sys.time(), tz = "UTC", usetz = TRUE)
  start_elapsed <- proc.time()[["elapsed"]]
  message(sprintf("[%s] rendering %s", tutorial_id, order$rmd[[i]]))

  rscript <- file.path(R.home("bin"), "Rscript")
  if (file.exists("/usr/bin/time")) {
    exit_code <- system2(
      "/usr/bin/time",
      c(
        "-v", "-o", shQuote(time_path),
        shQuote(rscript), shQuote(script_path), "--render-one", tutorial_id
      ),
      stdout = log_path,
      stderr = log_path
    )
  } else {
    exit_code <- system2(
      rscript,
      c(shQuote(script_path), "--render-one", tutorial_id),
      stdout = log_path,
      stderr = log_path
    )
  }
  ended <- format(Sys.time(), tz = "UTC", usetz = TRUE)
  duration <- proc.time()[["elapsed"]] - start_elapsed
  peak_kb <- NA_integer_
  if (file.exists(time_path)) {
    time_lines <- readLines(time_path, warn = FALSE)
    peak_line <- grep("Maximum resident set size", time_lines, value = TRUE)
    if (length(peak_line)) {
      peak_kb <- as.integer(trimws(sub("^.*:", "", peak_line[[1]])))
    }
  }

  runtime_sha <- if (file.exists(paths$runtime)) sha256_file(paths$runtime) else NA_character_
  record <- data.frame(
    order = order$order[[i]],
    tutorial_id = tutorial_id,
    rmd = order$rmd[[i]],
    status = if (identical(exit_code, 0L) && file.exists(paths$output_html)) "PASS" else "FAIL",
    exit_code = as.integer(exit_code),
    started_utc = started,
    ended_utc = ended,
    duration_seconds = round(duration, 3),
    peak_rss_kb = peak_kb,
    original_rmd_sha256 = sha256_file(paths$original),
    runtime_rmd_sha256 = runtime_sha,
    environment_lock_sha256 = environment_sha,
    input_adapter = paths$input_adapter,
    strict_material_status = paths$strict_material_status,
    strict_material_issue = paths$strict_material_issue,
    adapted_input_sha256 = paths$adapted_input_sha256,
    rendered_html = paths$output_html,
    log = log_path,
    stringsAsFactors = FALSE
  )
  if (nrow(records)) {
    records <- records[records$tutorial_id != tutorial_id, , drop = FALSE]
  }
  records <- rbind(records, record)
  records <- write_records(records)

  if (!identical(record$status[[1]], "PASS")) {
    stop(sprintf("%s failed; inspect %s", tutorial_id, log_path))
  }
  message(sprintf("[%s] PASS in %.1f seconds", tutorial_id, duration))
}

message("official tutorial rendering: PASS (8/8)")
